language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --exclude-group database,outbound --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)