version: '3'
services:
  php:
    image: search2d/php:7.1.9-1
    depends_on:
      - db
    volumes:
      - ./:/var/www:delegated
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini
    working_dir: /var/www
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=root
